# Generated by Django 2.2.3 on 2019-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=None, max_length=64, verbose_name='邮箱账号'),
        ),
    ]
