# Generated by Django 2.2.3 on 2019-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='邮箱账号'),
        ),
    ]
