# Generated by Django 2.2.3 on 2019-08-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='电池类型名称')),
                ('price_policy', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='价格策略')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_num', models.IntegerField(unique=True, verbose_name='设备编号')),
                ('slots1', models.SmallIntegerField(choices=[(0, '空闲'), (1, '使用中')], verbose_name='一号插槽')),
                ('slots2', models.SmallIntegerField(choices=[(0, '空闲'), (1, '使用中')], verbose_name='二号插槽')),
                ('slots3', models.SmallIntegerField(choices=[(0, '空闲'), (1, '使用中')], verbose_name='三号插槽')),
                ('slots4', models.SmallIntegerField(choices=[(0, '空闲'), (1, '使用中')], verbose_name='四号插槽')),
                ('slots5', models.SmallIntegerField(choices=[(0, '空闲'), (1, '使用中')], verbose_name='五号插槽')),
                ('slots6', models.SmallIntegerField(choices=[(0, '空闲'), (1, '使用中')], verbose_name='六号插槽')),
                ('city', models.CharField(max_length=16, verbose_name='城市')),
                ('addr', models.CharField(max_length=255, verbose_name='地址')),
            ],
        ),
    ]
