# Generated by Django 2.2.3 on 2019-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_auto_20190806_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='addr',
            field=models.CharField(max_length=255, null=True, verbose_name='地址'),
        ),
    ]
