# Generated by Django 2.2.3 on 2019-08-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(unique=True, verbose_name='订单编号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户')),
            ],
        ),
    ]
